{"levelname": "ERROR", "asctime": "2017-10-20 14:32:54,505", "message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/django/core/handlers/exception.py\", line 41, in inner\n    response = get_response(request)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/django/utils/deprecation.py\", line 142, in __call__\n    response = self.process_response(request, response)\n  File \"/home/arun/test/project/idcard/src/common/libraries/middleware.py\", line 64, in process_response\n    logger.debug('Response data for {0}: {1}'.format(request.get_full_path(), data))\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u2013' in position 65: ordinal not in range(128)", "status_code": 500, "request": "<WSGIRequest: GET '/'>"}
{"levelname": "ERROR", "asctime": "2017-10-20 14:32:57,764", "message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/django/core/handlers/exception.py\", line 41, in inner\n    response = get_response(request)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/django/utils/deprecation.py\", line 142, in __call__\n    response = self.process_response(request, response)\n  File \"/home/arun/test/project/idcard/src/common/libraries/middleware.py\", line 64, in process_response\n    logger.debug('Response data for {0}: {1}'.format(request.get_full_path(), data))\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u2013' in position 65: ordinal not in range(128)", "status_code": 500, "request": "<WSGIRequest: GET '/'>"}
{"levelname": "ERROR", "asctime": "2017-10-20 14:32:58,764", "message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/django/core/handlers/exception.py\", line 41, in inner\n    response = get_response(request)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/django/utils/deprecation.py\", line 142, in __call__\n    response = self.process_response(request, response)\n  File \"/home/arun/test/project/idcard/src/common/libraries/middleware.py\", line 64, in process_response\n    logger.debug('Response data for {0}: {1}'.format(request.get_full_path(), data))\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u2013' in position 65: ordinal not in range(128)", "status_code": 500, "request": "<WSGIRequest: GET '/'>"}
